; bB level data - Level 1
; Generated by editor export (manual for testing)

; Level metadata: start_room, start_x, start_y, miner_room, miner_x, miner_y,
;                 num_rooms, pf_color, bg_color
data _L1_META
  0, 16, 4, 2, 26, 20, 3, $2A, $02
end

; Room 0 - Starting room (open top, shaft at bottom center)
data _L1_R0_PF
  $00,$00, $00,$00, $FF,$FF, $81,$81, $81,$81, $81,$81,
  $81,$81, $81,$81, $81,$81, $81,$81, $81,$81, $00,$00
end

; Room 0 enemies: count, {type,x,y,range_min,range_max}...
data _L1_R0_EN
  1
  0,32,6,4,20
end

; Room 0 lamps: count, {x,y}...
data _L1_R0_LM
  0
end

; Room 1 - Middle room (shaft top, platform with fragile wall)
data _L1_R1_PF
  $00,$00, $00,$00, $FF,$FF, $81,$81, $81,$81, $C3,$C3,
  $C3,$C3, $81,$81, $81,$81, $81,$81, $81,$81, $00,$00
end

; Room 1 enemies
data _L1_R1_EN
  1
  1,24,8,16,32
end

; Room 1 lamps
data _L1_R1_LM
  0
end

; Room 2 - Miner room (shaft top, miner at bottom right)
data _L1_R2_PF
  $00,$00, $00,$00, $FF,$FF, $81,$81, $81,$81, $81,$81,
  $81,$81, $81,$81, $81,$81, $81,$81, $FF,$FF, $00,$00
end

; Room 2 enemies
data _L1_R2_EN
  1
  0,20,12,12,28
end

; Room 2 lamps
data _L1_R2_LM
  0
end
